### PR TITLE
Add Form

### PR DESCRIPTION
**Pull request by Dinma-Faith-zz**
In this PR, I

 * Created `current_user` method in the application controller
 * Create forms for adding posts and comments
 * Allow user to add likes to a post

### CODE REVIEW

**Review by RolandM99 — CHANGES_REQUESTED** [review]
Hi @Dinma-Faith, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Gitflow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] [**REQUIRED**] Kindly, make sure that you implemented your `views/user/index.html.rb` file well so that we can see the user created. For now, even I create a user from the rails console, in the browser, the UI still a blank page with only the text "Display Users:" as you can see below: 
image
For now, I can't proceed to check if your form for posts and comments works as expected because of this issue. Kindly, fix it.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Dinma-Faith-zz** [comment]
@RolandM99 thanks for the review. However, I think there's an issue on your end. The code works perfectly on my side. If you could please get on a call with me, it'd be a great help.

**Comment by RolandM99** [comment]
Kindly, can you please send me a screenshot of your page with the path `users/user_id` so that I can see if it works?

**Comment by Dinma-Faith-zz** [comment]
image (1)

**Comment by Dinma-Faith-zz** [comment]
image (2)

**Comment by RolandM99** [comment]
- Great, dear @Dinma-Faith ,  you can now resubmit your PR for a re-review.
Thanks,

**Review by uwadonat — APPROVED** [review]
## Hi @Dinma-Faith,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
### Highlights
- Your project works as expected ✔️
- No linter errors ✔️
- Professional readme file ✔️
cong

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
